{{- if .Values.storage.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "orbo.fullname" . }}-frames
  labels:
    {{- include "orbo.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size }}
  {{- if .Values.storage.persistence.storageClass }}
  storageClassName: {{ .Values.storage.persistence.storageClass }}
  {{- end }}
{{- end }}
