{{- if .Values.recognition.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orbo.fullname" . }}-recognition
  labels:
    {{- include "orbo.labels" . | nindent 4 }}
    app.kubernetes.io/component: recognition-service
spec:
  type: {{ .Values.recognition.service.type }}
  ports:
    - port: {{ .Values.recognition.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "orbo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: recognition-service
{{- end }}
