{{- if or .Values.secrets.telegramBotToken .Values.secrets.telegramChatId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orbo.fullname" . }}-secrets
  labels:
    {{- include "orbo.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.telegramBotToken }}
  telegram-bot-token: {{ .Values.secrets.telegramBotToken | b64enc }}
  {{- end }}
  {{- if .Values.secrets.telegramChatId }}
  telegram-chat-id: {{ .Values.secrets.telegramChatId | b64enc }}
  {{- end }}
{{- end }}