{{- $botToken := .Values.secrets.telegramBotToken | default .Values.notifications.telegram.botToken }}
{{- $chatId := .Values.secrets.telegramChatId | default .Values.notifications.telegram.chatId }}
{{- if or $botToken $chatId }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orbo.fullname" . }}-secrets
  labels:
    {{- include "orbo.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $botToken }}
  telegram-bot-token: {{ $botToken | b64enc }}
  {{- end }}
  {{- if $chatId }}
  telegram-chat-id: {{ $chatId | b64enc }}
  {{- end }}
{{- end }}